-- Criar tabela de categorias
CREATE TABLE categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Criar tabela de produtos
CREATE TABLE produtos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  descricao TEXT,
  preco FLOAT8,
  imagem TEXT,
  "categoriaId" BIGINT REFERENCES categorias(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);